/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;


import fatec.poo.model.Atendente;
import fatec.poo.model.Hospede;
import fatec.poo.model.QuartoHotel;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author Priscila
 */
public class GuiReservarLiberacao extends javax.swing.JFrame {

    /**
     * Creates new form GuiReservarLiberacao
     */
    public GuiReservarLiberacao(ArrayList<QuartoHotel> hotel, ArrayList<Atendente> atendentes, ArrayList<Hospede> hospedes) {
        initComponents();
        cadastro = hotel;
        atendenteFunc = atendentes;
        hospedeCPF = hospedes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        txtRegFunc = new javax.swing.JTextField();
        txtCPFHospede = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNQuarto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDataEntrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDataSaida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnPesquisaRegFunc = new javax.swing.JButton();
        btnPesquisaCPFHospede = new javax.swing.JButton();
        btnPesquisaNQuarto = new javax.swing.JButton();
        lblRegFunc = new javax.swing.JLabel();
        lblCPFHospede = new javax.swing.JLabel();
        lblValPag = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservar/Liberar Quarto");

        jLabel1.setText("Reg. Func.");

        txtCPFHospede.setEnabled(false);

        jLabel2.setText("CPF Hóspede");

        txtNQuarto.setEnabled(false);

        jLabel3.setText("N°. Quarto");

        jLabel4.setText("Situação");

        txtDataEntrada.setEnabled(false);

        jLabel5.setText("Data Entrada");

        txtDataSaida.setEnabled(false);

        jLabel6.setText("Data Saída");

        jLabel7.setText("Valor a Pagar");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnPesquisaRegFunc.setText("...");
        btnPesquisaRegFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaRegFuncActionPerformed(evt);
            }
        });

        btnPesquisaCPFHospede.setText("...");
        btnPesquisaCPFHospede.setEnabled(false);
        btnPesquisaCPFHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCPFHospedeActionPerformed(evt);
            }
        });

        btnPesquisaNQuarto.setText("...");
        btnPesquisaNQuarto.setEnabled(false);
        btnPesquisaNQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaNQuartoActionPerformed(evt);
            }
        });

        lblRegFunc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblCPFHospede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblValPag.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblSituacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(21, 21, 21)
                                        .addComponent(txtNQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPesquisaNQuarto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtRegFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCPFHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPesquisaCPFHospede)
                                            .addComponent(btnPesquisaRegFunc))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRegFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCPFHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReservar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLiberar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValPag, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPesquisaCPFHospede, btnPesquisaNQuarto, btnPesquisaRegFunc});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReservar)
                            .addComponent(btnLiberar)
                            .addComponent(btnSair))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtRegFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPesquisaRegFunc)))
                            .addComponent(lblRegFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCPFHospede, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtCPFHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPesquisaCPFHospede)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtNQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(btnPesquisaNQuarto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValPag, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(151, 151, 151))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPesquisaCPFHospede, btnPesquisaNQuarto, btnPesquisaRegFunc});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisaRegFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaRegFuncActionPerformed
        
        //OK        
        int i;

        for (i = 0; i < atendenteFunc.size(); i++) {
            if(txtRegFunc.getText().equals(atendenteFunc.get(i).getRegFunc())){ 
                break;
            }
        }

        if(i < atendenteFunc.size()){
            posAtendente = i;
        }else{
            posAtendente = -1;
        }

        if(posAtendente >=0){
            lblRegFunc.setText(atendenteFunc.get(posAtendente).getNome());
            txtRegFunc.setEnabled(false);
            btnPesquisaRegFunc.setEnabled(false);
            txtCPFHospede.setEnabled(true);
            btnPesquisaCPFHospede.setEnabled(true);
            txtCPFHospede.requestFocus();            
        }else{
            lblRegFunc.setText("Atendente não cadastrado");              
        }                  
    }//GEN-LAST:event_btnPesquisaRegFuncActionPerformed

    private void btnPesquisaCPFHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCPFHospedeActionPerformed

        //Ok
        int x;    

        for (x = 0; x < hospedeCPF.size(); x++){             
            if (txtCPFHospede.getText().equals(hospedeCPF.get(x).getCpf())){
                break;
            }                
        }
        
        if(x < hospedeCPF.size()){
            posHospede = x;
        }else{
            posHospede = -1;
            lblCPFHospede.setText("Hóspede não cadastrado"); 
        }
        if(posHospede >= 0){
            lblCPFHospede.setText(hospedeCPF.get(posHospede).getNome());
            txtCPFHospede.setEnabled(false);
            btnPesquisaCPFHospede.setEnabled(false); 
            
            if(hospedeCPF.get(posHospede).getQuartoHotel() != null){
                txtNQuarto.setText(String.valueOf(hospedeCPF.get(posHospede).getQuartoHotel().getNumQuarto()));
                lblSituacao.setText(String.valueOf(hospedeCPF.get(posHospede).getQuartoHotel().isSituacao()));
                txtDataEntrada.setText(hospedeCPF.get(posHospede).getQuartoHotel().getDataEntrada());
                txtDataSaida.setEnabled(true);
                btnLiberar.setEnabled(true);                                    
            }
            else{
                txtNQuarto.setEnabled(true);
                btnPesquisaNQuarto.setEnabled(true);                   
            }
        }        
    }//GEN-LAST:event_btnPesquisaCPFHospedeActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        
        //Ok
        int x;
        
        for(x = 0; x < cadastro.size(); x++){
            if (txtNQuarto.getText().equals(String.valueOf(cadastro.get(x).getNumQuarto()))){        
                break;
            }
        }
                
        if(x < cadastro.size()){
            posQuartoHotel = x;
        }else{
            posQuartoHotel = -1;
        }
        
        if(posQuartoHotel >= 0){
            
            cadastro.get(posQuartoHotel).setDataEntrada(txtDataEntrada.getText());
            
            cadastro.get(posQuartoHotel).reservar(hospedeCPF.get(posHospede), atendenteFunc.get(posAtendente));

            txtRegFunc.setText(null);
            lblRegFunc.setText(null);

            txtCPFHospede.setText(null);
            lblCPFHospede.setText(null);

            txtNQuarto.setText(null);
            txtNQuarto.setEnabled(false);            
            btnPesquisaNQuarto.setEnabled(false);
            lblSituacao.setText(null);

            txtDataEntrada.setText(null);
            txtDataEntrada.setEnabled(false);

            btnReservar.setEnabled(false);                
            txtRegFunc.setEnabled(true);
            btnPesquisaRegFunc.setEnabled(true);            
        }
        
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnPesquisaNQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaNQuartoActionPerformed
        //ok
        int x;    
            
        for(x = 0; x < cadastro.size(); x++){
            if (txtNQuarto.getText().equals(String.valueOf(cadastro.get(x).getNumQuarto()))){
                break;
            }
        }
        
        if(x < cadastro.size()){
            posQuartoHotel = x;
        }else{
            posQuartoHotel = -1;
        }
        
        if(posQuartoHotel >= 0){
            if(cadastro.get(posQuartoHotel).isSituacao() == false){
                lblSituacao.setText("Livre"); 
                txtDataEntrada.setEnabled(true);
                btnReservar.setEnabled(true);
            }else{
                lblSituacao.setText("Quarto Ocupado");   
            }
        }
        else{
            lblSituacao.setText("Quarto não cadastrado");
            txtDataEntrada.setEnabled(false);            
        }
    }//GEN-LAST:event_btnPesquisaNQuartoActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
       // Ok
        DecimalFormat df = new DecimalFormat("#,##0.00");
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar data1 = Calendar.getInstance();
        Calendar data2 = Calendar.getInstance();
        int dias;
        try {                
                            
            data1.setTime(sdf.parse(txtDataEntrada.getText()));
            data2.setTime(sdf.parse(txtDataSaida.getText()));
             
        } catch (java.text.ParseException e ) { }
       
        dias = data2.get(Calendar.DAY_OF_YEAR) - data1.get(Calendar.DAY_OF_YEAR);


        
        lblValPag.setText(df.format(cadastro.get(posQuartoHotel).liberar(dias, hospedeCPF.get(posHospede).getTxDesconto())));
        hospedeCPF.get(posHospede).setQuartoHotel(null);
            
        txtRegFunc.setText(null);
        lblRegFunc.setText(null);
        
        txtCPFHospede.setText(null);
        lblCPFHospede.setText(null);
        
        txtNQuarto.setText(null);
        
        txtDataEntrada.setText(null);
        
        txtDataSaida.setText(null);            
        txtDataSaida.setEnabled(false);
        
        lblSituacao.setText(null);
        
        btnLiberar.setEnabled(false);
        btnReservar.setEnabled(true);         
        txtRegFunc.setEnabled(true);
        btnPesquisaRegFunc.setEnabled(true);
            
    }//GEN-LAST:event_btnLiberarActionPerformed
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnPesquisaCPFHospede;
    private javax.swing.JButton btnPesquisaNQuarto;
    private javax.swing.JButton btnPesquisaRegFunc;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCPFHospede;
    private javax.swing.JLabel lblRegFunc;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblValPag;
    private javax.swing.JTextField txtCPFHospede;
    private javax.swing.JTextField txtDataEntrada;
    private javax.swing.JTextField txtDataSaida;
    private javax.swing.JTextField txtNQuarto;
    private javax.swing.JTextField txtRegFunc;
    // End of variables declaration//GEN-END:variables
    private ArrayList<QuartoHotel> cadastro;
    private ArrayList<Atendente> atendenteFunc;
    private ArrayList<Hospede> hospedeCPF;
    private int posQuartoHotel;
    private int posAtendente;
    private int posHospede;
}
